language: python

python:
  - "3.6"

services:
  - postgresql

install: "pip install -r requirements.txt"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c 'CREATE USER test WITH PASSWORD 'test';' -U postgres
  - psql -c 'ALTER USER test CREATEDB;' -U postgres

script:
- SECRET_KEY="whatever" ./manage.py test